alias updt='sudo apt-get update'
alias upgrd='sudo apt-get upgrade'
alias gst='git status'
alias gf='git fetch'
alias gb='git branch'
alias gsno='git show --name-only --pretty='
alias grh='git reset --hard'
alias gu='git add -u'
alias gc='git commit'
alias gck='git checkout'
